spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/lider_test_task
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        default_batch_fetch_size: 100
  liquibase:
    enabled: true
