spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/lider_test_task
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false