create table sport_type
(
    id   int8 generated by default as identity primary key,
    name varchar(255) not null unique
);

create table team
(
    id            int8 generated by default as identity primary key,
    date          date         not null,
    name          varchar(255) not null,
    sport_type_id int8 not null,
    constraint FK_team_sport_type foreign key (sport_type_id) references sport_type,
    constraint unique_name_type unique (name, sport_type_id)
);

create table athlete
(
    id         int8 generated by default as identity primary key,
    date       date        not null,
    name       varchar(50) not null,
    last_name  varchar(50) not null,
    patronymic varchar(50),
    position   varchar(50) not null,
    team_id    int8        not null,
    constraint FK_athlete_team foreign key (team_id) references team,
    constraint unique_name_last_name_position_team_id unique (name, last_name, position, team_id)
);